### ISSUE TITLE
Error indexing with Bool or BitArray

### ISSUE THREAD

**Issue by diegozea** [nalimilan/FreqTables.jl#10]
I'm getting the following error while I'm trying to index the table with a `BitArray` or an `Array{Bool,1}`:

![image](https://cloud.githubusercontent.com/assets/2822757/17460596/e78f082a-5c44-11e6-9eb8-5cca2cf474f8.png)

**Comment by nalimilan** [comment]
Thanks, but again this sounds like a NamedArray bug. Please report it there, if possible with a reproducible example.

Cc: @davidavdav

**Comment by davidavdav** [comment]
Yep this is a NamedArrays bug.   I'll try to install Gallium this time to see if I can single step into the routine to find out what the dispatch sequence is.

**Comment by davidavdav** [comment]
I hope this is now fixed in https://github.com/davidavdav/NamedArrays.jl/commit/fd0bc2ff681ab6fa973b5863285d7e918ce76927 . 

It is non-trivial to reproduce the Julia slicing/dimension dropping semantics across julia-0.4 and julia-0.5 .  There are probably some forms of indexing where things still go wrong.
