### ISSUE TITLE
Formula support

### ISSUE THREAD

**Issue by diegozea** [nalimilan/FreqTables.jl#6]
Would be great to support DataFrames' `Formula`

```julia
julia> tbl = dataset("MASS","survey");

julia> freqtable(tbl, :Smoke, :Exer)
4x3 NamedArray{Int64,2}:
Smoke ╲ Exer │ Freq  None  Some
─────────────┼─────────────────
Heavy        │    7     1     3
Never        │   87    18    84
Occas        │   12     3     4
Regul        │    9     1     7

julia> freqtable(tbl, Smoke ~ Exer)
ERROR: MethodError: `freqtable` has no method matching freqtable(::DataFrames.DataFrame, ::DataFrames.Formula)
Closest candidates are:
  freqtable(::DataFrames.DataFrame, ::Symbol...)
```

**Comment by nalimilan** [comment]
Actually, I don't see the point of that syntax for frequency tables. It has no real meaning here, since there's no dependent and independent variable. The syntax that the R survey package uses is `~ Smoke + Exer`, but that's not really clear, and it's more verbose than just listing the variables. What's the problem with the current syntax?

**Comment by diegozea** [comment]
That's true, `Formula` syntax isn't a win here. I'll close this.
